# Generated by Django 4.1.5 on 2023-02-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_videos_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='poster',
            field=models.ImageField(default=1, upload_to='post_poster/'),
            preserve_default=False,
        ),
    ]
